export const initialState = {
  interval: null,
  time: null,
  currency: null,
  from: '',
  to: '',
  playerId: '',
  eventId: '',
  shop_id: '',
  packageId: '',
  payoutOption: null,
  //   contentCount: [ null, null ],
  //   amount: [ null, null ],
  //   win: [ null, null ],
  status: null,
  sport: null,
  source: null,
  ticketKind: null,
  market_type: null,
};
